### ISSUE TITLE
Lighthouse Check

### ISSUE THREAD

**Issue by nvhiii** [nvhiii/my_scheduler#3]
### Lighthouse Checks
- [ ] #6
- [ ] [Design new landing page](https://github.com/octocat/octoproject/issues/4)
- [ ] [Translate content into supported languages](https://github.com/octocat/octoproject/issues/11)
- [ ] more tba

**Comment by nvhiii** [comment]
- [x] [Design new landing page](https://github.com/octocat/octoproject/issues/4)
- [ ] [Translate content into supported languages](https://github.com/octocat/octoproject/issues/11)
- [ ] make sure to check unused code (js, css, html, and properly formatted images)
